{"name": "test_ddt_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Fail' not in ['Pass', 'Fail', 'Pass', 'Pass']", "trace": "self = <testCases.test_login_ddt.Test_002_DDT_Login object at 0x0459A230>\nsetup = <selenium.webdriver.edge.webdriver.WebDriver (session=\"6aff58481e614c600199a02c035a21ea\")>\n\n    def test_ddt_login(self, setup):\n        self.logger.info(\"******** Verifying DDT Login Test ********\")\n        self.driver = setup\n        self.driver.get(self.baseURL)\n        self.loginpage = LoginPage(self.driver)\n    \n        self.rows = ExcelUtil.get_rowcount(self.path, 'Sheet1')\n        print(self.rows)\n    \n        lst_status = []\n        for r in range(2, self.rows+1):\n            self.user = ExcelUtil.read_data(self.path, 'Sheet1', r, 1)\n            self.password = ExcelUtil.read_data(self.path, 'Sheet1', r, 2)\n            self.exp = ExcelUtil.read_data(self.path, 'Sheet1', r, 3)\n    \n            self.loginpage.setUserName(self.user)\n            self.loginpage.setPassword(self.password)\n            self.loginpage.clickLogin()\n            time.sleep(5)\n    \n            act_title = self.driver.title\n            exp_title = \"Dashboard / nopCommerce administration\"\n            if act_title == exp_title:\n                if self.exp == 'Pass':\n                    self.logger.info(\"******** Passed ********\")\n                    self.loginpage.clickLogout()\n                    lst_status.append('Pass')\n                elif self.exp == 'Fail':\n                    self.logger.info(\"******** Failed ********\")\n                    self.loginpage.clickLogout()\n                    lst_status.append('Fail')\n            elif act_title != exp_title:\n                if self.exp == 'Fail':\n                    self.logger.info(\"******** Passed ********\")\n                    lst_status.append('Pass')\n                elif self.exp == 'Pass':\n                    self.logger.info(\"******** Failed ********\")\n                    lst_status.append('Fail')\n    \n>       assert 'Fail' not in lst_status\nE       AssertionError: assert 'Fail' not in ['Pass', 'Fail', 'Pass', 'Pass']\n\ntestCases\\test_login_ddt.py:56: AssertionError"}, "attachments": [{"name": "log", "source": "97a57b52-6496-4875-9356-d3901e66ae0a-attachment.txt", "type": "text/plain"}], "start": 1620634605513, "stop": 1620634642980, "uuid": "deab829b-242b-4ffa-8196-65b373cf630f", "historyId": "99fc1ec5c8243f6fde243ef4141e6ca6", "testCaseId": "02be95dfe83070bb2b2a1952ae7e0374", "fullName": "testCases.test_login_ddt.Test_002_DDT_Login#test_ddt_login", "labels": [{"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_login_ddt"}, {"name": "subSuite", "value": "Test_002_DDT_Login"}, {"name": "host", "value": "DESKTOP-EU8OBTK"}, {"name": "thread", "value": "2652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_login_ddt"}]}